//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Aranzman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aranzman()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
        }

        public int AranzmanID { get; set; }
        public int HotelID { get; set; }
        public int UslugaID { get; set; }
        public int TerminID { get; set; }

        [Required(ErrorMessage = "Cena je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Cena mora da bude ceo broj")]
        [Range(1, 9999, ErrorMessage = "Cena mora da bude veća od nule")]
        public int Cena { get; set; }

        [Required(ErrorMessage = "Raspoloživost je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Raspoloživost mora da bude ceo broj")]
        [Range(1, 9999, ErrorMessage = "Raspoloživost mora da bude veća od nule")]
        public int Raspolozivost { get; set; }

        public int Aktivan { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Termin Termin { get; set; }
        public virtual Usluga Usluga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
