//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Destinacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Destinacija()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int DestinacijaID { get; set; }

        [Required(ErrorMessage = "Ime zemlje je obavezno")]
        //[RegularExpression ("[a-zA-Z]+", ErrorMessage = "Ime zemlje sadrži samo slova")]
        public string Zemlja { get; set; }

        [Required(ErrorMessage = "Ime grada je obavezno")]
        //[RegularExpression("[a-zA-Z]+", ErrorMessage = "Ime grada sadrži samo slova")]
        public string Grad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
