//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Aranzmen = new HashSet<Aranzman>();
        }

        public int HotelID { get; set; }

        [Required(ErrorMessage = "Naziv hotela je obavezan")]
        public string Naziv { get; set; }

        [Required(ErrorMessage = "Broj zvezdica je obavezan")]
        [Range(1, 5, ErrorMessage = "Unesite broj zvezdica od 1 do 5")]
        [RegularExpression("[1-5]", ErrorMessage =("Unesite broj zvezdica od 1 do 5"))]
        public int BrojZvezdica { get; set; }

        public int DestinacijaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aranzman> Aranzmen { get; set; }
        public virtual Destinacija Destinacija { get; set; }
    }
}
